services:
  web:
    container_name: backend_SIT
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery
    networks:
      - custom_network

  celery:
    container_name: celery_SIT
    build: .
    command: celery -A app.__init__:celery worker --loglevel=INFO --pool=solo
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - custom_network

  redis:
    container_name: redis_SIT
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - custom_network
      
networks:
  custom_network:
    driver: bridge


